### PR TITLE
Maintain locks and zippers from original PDB.

### PR DESCRIPTION
**Pull request by ssepeq**
Docking will no longer break apart any salt bridges, leucine zippers, or other locks in place unless the ligand would provide a better intermolecular bond.

### CODE REVIEW

**Comment by ssepeq** [comment]
Bug: The dock keeps bringing heavy atoms way too close together. This is especially causing the amino aldehyde test to seriously fail.

**Comment by ssepeq** [comment]
🟩🟥🟩

**Comment by ssepeq** [comment]
🟩🟨🟨

The TAAR8 and OR1A1 tests do work, but intermittently. The dock doesn't always find a good pose, likely because the ligand keeps ending up bumped up against the coordination residues.

**Comment by ssepeq** [comment]
🟩🟩🟩

**Review by primaryodors — CHANGES_REQUESTED** [review]
This PR does not accomplish its intended purpose: "Maintain locks and zippers from original PDB.".

image 
image 
image

The salt bridge between Asn111 and His243 in OR1A1 should remain like it is in the input PDB:
image

**Comment by ssepeq** [comment]
🟩🟥🟩

**Comment by ssepeq** [comment]
TAAR8 test is failing because of the Y116 - D201 hydrogen bond. Y116 is clashing with the ligand but not always producing a negative binding energy, therefore forbidding residue flexion. The docker compromises by moving the ligand out of the way, resulting in incorrect poses (and incidentally no poses within energy limits).

**Comment by ssepeq** [comment]
Abandoning this.

**Pull request closed without merging**
