### PR TITLE
More cron stuff.

### PR DESCRIPTION
**Pull request by ssepeq**
The cron got stuck on OR3A1 making zero progress so these changes attempt to remedy that.

### CODE REVIEW

**Comment by ssepeq** [comment]
The OR3A1+hGNAS2 model is misshapen. TMR5 and TMR6 are clashing in the ligand binding site.

image

image

image

**Comment by ssepeq** [comment]
A unit test will be necessary on this PR.

**Comment by ssepeq** [comment]
The TAAR test keeps failing for some stupid reason and I'd be able to find it and fix it if not for this STUPID SOCIAL EVENT THAT OCCURS SPORADICALLY, I HAVE ZERO INTEREST IN, I DON'T ENJOY GOING TO, AND CAN'T ^%$@# GET OUT OF HAVING TO GO TO! 😡😡😡😡😡😡😡😡😡😡😡😡

**Comment by primaryodors** [comment]
Github's code editor is pretty much unusable, anyway go ahead and merge `ucase-aa3let` into this branch. @ssepeq

**Comment by ssepeq** [comment]
Success! Casting the numbers to chars didn't work, but the strcpy() method does.

**Comment by primaryodors** [comment]
Great! How was the social event?

**Comment by ssepeq** [comment]
Painful.

Master unit test succeeded! Going to let the cron run through all the couples and see how it does in the predictions before marking this ready.

**Comment by ssepeq** [comment]
Looks like several G proteins are expressed in mammalian OSNs, but it's difficult to know which ones couple with ORs in the real world. https://doi.org/10.1093/chemse/bjw003

**Comment by ssepeq** [comment]
Also seeing a lot of proteins where the extracellular end of TMR6 has room to rock inward more and make contact between Y6.55 and D/E45.51, but doesn't presumably because TMR7 would clash with TMR2.

image

**Comment by primaryodors** [comment]
Go ahead and merge `287-coplanar-hydrogenation` into the branch for this PR. @ssepeq

**Comment by ssepeq** [comment]
Merged.

**Comment by ssepeq** [comment]
Maybe not necesary to get ORs binding to hGNAO1, since they might not bind in the real world. TAARs are known to bind to it, and TAAR5 seems to work ok.

https://en.wikipedia.org/wiki/Heterotrimeric_G_protein

**Comment by ssepeq** [comment]
GNAO1 seems to be involved in the inhibition of olfactory neurons. https://doi.org/10.1016%2Fj.mcn.2020.103585

This is not surprising since according to the Wikipedia link, GNAO1 signalling has the effect of closing Ca2+ channels, which are measured in some of the receptor-odorant assays. So some odorants that give a false positive prediction of being agonists but are actually antagonists or inverse agonists, might be better at binding to the GNAO1-bound OR vs. the GNAL- or GNAS2-bound receptor.

**Comment by ssepeq** [comment]
This PR is getting out of hand. Running master unit test in preparation to mark this ready.

**Comment by ssepeq** [comment]
Master unit test succeeded.

**Comment by primaryodors** [comment]
What's the status of this PR?

**Pull request closed without merging**
