### PR TITLE
Unit tests.

### PR DESCRIPTION
**Pull request by ssepeq**
Created a master unit test that runs the big 3 tests. TODO: Check output of docks.

Plenty more work to be done on this. See #257 .

### CODE REVIEW

**Comment by primaryodors** [comment]
Any new progress on this? @ssepeq

**Comment by ssepeq** [comment]
Going to be afk for several days this week and next. Want to get protein coupling working reliably and then have coupled PDBs ready and docking running on a cron on the local server, that way there'll be docks ready for analysis on my return.

**Comment by primaryodors** [comment]
Going to want to include `test/motif_test.pepd` in the master unit test.

**Comment by primaryodors** [comment]
While the server is performing large numbers of docks, now would be a great time to resume the unit tests.

**Comment by ssepeq** [comment]
Molecular assembly is a crazy bizarre funhouse right now! Here's one example:

image

Another bug is saturated rings (cyclohexane etc) aren't working. It makes a straight chain hydrocarbon and then bonds the ends together, but doesn't curl it into a ring. I think that one might be a not too difficult fix in order to get mol_assem_test working.

**Comment by primaryodors** [comment]
Don't worry too much right now about the molecule assembly tests that are failing; recall that some SMILES strings have never worked in the classes and that's why we integrated with OpenBabel.

Any tests that are failing should be left commented out for now. If a test can be fixed with just one or two lines of code, that's fine to include, but anything more than that is out of scope for this PR.

**Comment by ssepeq** [comment]
☹️ 

Turning off debugging and checking in molecule assembly changes so far...

**Comment by primaryodors** [comment]
These tests are looking good. If you can think of anything else to add, go for it, otherwise this master test looks good enough to start with.

The express test can include everything except the TAAR8 and OR1A1 tests. Once that is ready, feel free to mark this for review.

**Comment by ssepeq** [comment]
Even the protein test and motif test? They each take a moment to run.

**Comment by primaryodors** [comment]
The protein test, motif test, and molecule assembly tests can be omitted from the express test.

**Review by primaryodors — APPROVED** [review]

**Comment by primaryodors** [comment]
The Big Three test is now obsolete; all future PRs will be required to pass unit_test_master (i.e. it should not output any red text) before merge.

**Pull request merged**
