### PR TITLE
Hydrophobic cohesion.

### PR DESCRIPTION
**Pull request by ssepeq**
A.k.a. oil cuddling. Hydrophobic atoms will now exhibit a strong tendency to stick together, since their surroundings will be assumed to be predominantly hydrophilic as they are in olfactory receptor EXR and CYT regions, and in the spaces between the TM helices.

A new constant named `oxytocin` mediates the effect, in order to balance the amino aldehyde test, which prefers low values of the new constant, and the following dialkane test, which prefers high values:

`clear; make test/molecule_test && ./test/molecule_test 'CCCCCC' 'CCCCCC'`

A successful dialkane result shows the two chains lined up side by side, e.g.:

image

### CODE REVIEW

**Comment by ssepeq** [comment]
TODO:

- Currently the cohesion effect affects all atoms. It should be modified to affect only nonpolar atoms.
- Currently the effect is "always-on". It would be best to add a boolean that the effect can be turned on and off.
- Even better would be the ability to define spherical and cylindrical regions where the effect takes place.

**Comment by ssepeq** [comment]
🟩🟩🟨

**Comment by ssepeq** [comment]
🟩🟩...

**Comment by ssepeq** [comment]
🟩🟩...

**Comment by ssepeq** [comment]
I am going to think more on the inclusion and exclusion zones. For now, here's the simple version of the feature.

**Comment by primaryodors** [comment]
Should enable the new feature for the TAAR8 and OR1A1 tests.

**Comment by ssepeq** [comment]
🟩🟩🟩

**Comment by primaryodors** [comment]
Checking this out with propionate (strong agonist), hexanoate (non-agonist), and octanoate (non-agonist) in OR51E2.

image
image
image

Both the C6 and C8 acids have a tendency to orient themselves in a more vertical/diagonal position, which would draw the TM6 helix in closer. Predicting these protein-ligand pairs might involve guided docking (a feature planned but not yet written), and might not reveal a more favorable energy in the inactive state, but rather any gain in energy for the active state might fail to meet a certain threshold value determined by the protein structure.

**Pull request merged**
