### PR TITLE
Test config files for known receptor-ligand pairs.

### PR DESCRIPTION
**Pull request by ssepeq**
OR1A1 d-limonene test.

### CODE REVIEW

**Comment by ssepeq** [comment]
The butyrate one is doing something weird...

```
PDB file: pdbs/OR1/OR1A1.rotated.pdb
Ligand: sdf/butyrate.sdf


5 pose(s) found.

Calculation took: 4 seconds.
```

The ligand is an inverse agonist for the receptor, so it should dock inside the pocket in a way that does not cause receptor activation. However, the docker seems to just give up without even trying to dock it. Then it reports 5 poses (the maximum configured in the input file) but no actual PDB data on the screen or in the output file.

**Comment by ssepeq** [comment]
`make clean` fixed it.

**Comment by ssepeq** [comment]
The acetophenone one is still doing the strange behavior. This ligand-receptor pair is a non-agonist, however the docker should still return either a statement saying 0 poses or else PDB output for any poses that it does find.

**Comment by ssepeq** [comment]
Marking this ready since it contains a code fix for the docker.

**Review by primaryodors — APPROVED** [review]

**Pull request merged**
